global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    # metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['otel-collector:8889']
#Scrape the JMX Exporter
  - job_name: 'jmx-exporter'
    static_configs:
      - targets: ['host.docker.internal:9404']  # Replace with the actual host and port
